export const FETCH_QUIZES_START = "FETCH_QUIZES_START";
export const FETCH_QUIZES_SUCCESS = "FETCH_QUIZES_SUCCESS";
export const FETCH_QUIZES_ERROR = "FETCH_QUIZES_ERROR";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";
