import "handsontable/dist/handsontable.full.css";

import React from "react";
import { HotTable } from "@handsontable/react";

class App extends React.Component {
  constructor(props) {
    super(props);
    this.data = [
      [
        "500",
        "300",
        {
          data: "=B1+B2",
          readOnly: true
        },
        "=B3+B4",
        "=B5+B6",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ],

      [
        "500",
        "300",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ],
      [
        "500",
        "300",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ],
      [
        "500",
        "300",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ],
      [
        "500",
        "300",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ],
      [
        "500",
        "300",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ],
      [
        "500",
        "300",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ],
      [
        "500",
        "300",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ],
      [
        "500",
        "300",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ],
      [
        "500",
        "300",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ],
      [
        "500",
        "300",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ],
      [
        "500",
        "300",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ],
      [
        "500",
        "300",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ],
      [
        "500",
        "300",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ],
      [
        "500",
        "300",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2",
        "=A1+A2"
      ]
    ];
  }

  render() {
    console.log(this.data);
    return (
      <div id="hot-app">
        <HotTable
          data={this.data}
          colHeaders={[
            "Январь",
            "Февраль",
            "Март",
            "Апрель",
            "Май",
            "Июнь",
            "Июль",
            "Август",
            "Сентябрь",
            "Октябрь",
            "Ноябрь",
            "Декабрь"
          ]}
          rowHeaders={true}
          licenseKey="non-commercial-and-evaluation"
          formulas={true}
          // width="99vw"
          // height={400}
        />
      </div>
    );
  }
}

export default App;
